config/routes.rb
Rails.application.routes.draw do
  resources :blogs

  get '/blog_page/:blog_title', to: 'blogs_display#blog_page'
  get '/blog_home', to: 'blogs_display#blog_home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  before_save :set_title_url

  def set_title_url
    date = if self.created_at
	     self.created_at.to_date
	   else
	     Date.today
	   end
    underscored_title = "#{date}_#{self.title.gsub(' ','_')}".downcase
    self.title_url = sanitize_string_for_title_url(underscored_title) 
  end

  def sanitize_string_for_title_url(url_string)
    url_string.gsub!("'",'')
    url_string.gsub!("?",'')
    url_string.gsub!("!",'')
    url_string.gsub!(':','_')
    url_string.gsub!(';','_')
    url_string
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :summary, :content_html)
    end
end

app/controllers/blogs_display_controller.rb
class BlogsDisplayController < ApplicationController
  before_action :set_blog, only: [:blog_page]

  def blog_page
  end

  def blog_home
    @blogs = Blog.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
	    @blog = Blog.where(title_url: params[:blog_title].downcase).first
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_field :summary %>
  </div>

  <div class="field">
    <%= form.label :content_html %>
    <%= form.text_area :content_html, style: 'width: 600px; height: 800px;', id: 'textarea_editor' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table class='table table-striped table-bordered basic_datatable'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Title Url</th>
      <th>Summary</th>
      <th>Content html</th>
      <th>show</th>
      <th>edit</th>
      <th>destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
	<td><%= link_to blog.title_url, "/blog_page/#{blog.title_url}"  %></td>
        <td><%= blog.summary %></td>
	<td style='max-width:300px;'><pre><code class='html'><%= blog.content_html %></code></pre></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @blog.summary %>
</p>

<p>
  <strong>Content html:</strong>
  <pre>
    <code class='html'>
<%= @blog.content_html %>
    </code>
  <pre>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs_display/_blog_pagev2.html.erb
<div id='blog-pagev2_container'>
  <div class='blog-title_container'>
    <%= @blog.title.html_safe %>
  </div>
  <div class='blog-content_container'>
    <%= @blog.content_html.html_safe %>
  </div>
</div>

app/views/blogs_display/blog_home.html.erb
<div id='blog-home_container'>
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">Matt's Programming Blog</h1>
      <p class="lead">
        A blog to document what I have learned for your benefit and mine 
      </p>
    </div>
  </div>

  <div class='container'>
    <div class='row'>
	    
      <div id='featured_blogs_container' class='container col-sm-5'>
        <h1><u>Featured Blogs</u></h1>
        <% @blogs[0...4].each do |blog|%>
          <div class='blog_summary row'>
            <div class='col-sm-12'>		    
	      <h3><%= link_to blog.title, "/blog_page/#{blog.title_url}"  %></h3>
              <% max_length = 50 %>
              <% if blog.summary.length > max_length %>
	        <p>
	          <%= blog.summary[0...max_length] %><span class="dots">...</span><span class="more" style='display:none;'><%= blog.summary[max_length..-1] %></span>
	        </p>
                <button class='readmore_toggle'>Read more</button>
              <% else %>
	        <p>
	          <%= blog.summary %>
	        </p>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>

      <div id='all_blogs_container' class='col-sm-7'>
	<h1><u>All Blogs</u></h1>
	<div id='all_blogs_table_container'>
	  <table class='basic_datatable table table-striped table-bordered'>
	    <thead>
	      <tr>
                <th>Title</th>
	        <th>Summary</th>
		<th>Created On</th>
	      </tr>
	    </thead>
	    <tbody>
	      <% @blogs.each do | blog | %>
	        <tr>
                  <td><%= link_to blog.title, "/blog_page/#{blog.title_url}"  %></td>
      	          <td><%= blog.summary %></td> 
		  <td><%= blog.created_at.to_date %></td>
                </tr>
	      <% end %>
	    </tbody>
     	  </table>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/blogs_display/blog_page.html.erb
<%= render partial: 'blog_pagev2', locals: { blog: @blog } %>

app/views/blogs_display/partials/_blog_summary.html.erb
<div class='blog-summary_container'>
 <p><%= @blog.title %></p>
 <p><%= @blog.summary %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MattsBlog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="turbolinks-cache-control" content="no-cache"> 
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id='page_content_wrapper'>
      <%= yield %>
    </div>
    <%= render partial: '/layouts/partials/footer' %>
  </body>
</html>

app/views/layouts/partials/_floating_nav.html.erb
<div class='fixed-top'>
	hey
</div>

app/views/layouts/partials/_footer.html.erb
<footer class="page-footer font-small blue pt-4">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase">Footer Content</h5>
        <p>Here you can use rows and columns to organize your footer content.</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">
	  ©<%= Date.today.year %>  Copyright: <a href="#"> Somewhere.com</a>
  </div>
  <!-- Copyright -->

</footer>